### ISSUE TITLE
Autos

### ISSUE THREAD

**Issue by JuanFurlan** [pdepmartestm/me-presento-MartinZino#2]
Que tipo de autos te gustan mas, estilo mas clásicos, deportivos?
Te gusta la formula 1?

**Comment by MartinZino** [comment]
En realidad pueden ser ambos, un auto puede ser clásico y deportivo a la vez, por ejemplo el Toyota 2000 gt. Pero si, me encantan ambos, tanto clásicos como deportivos. No me gusta la formula 1, me gusta más el Rally. No modifico mi presentación porque considero que eso es una pregunta muy personal

**Comment by JuanFurlan** [comment]
Toda la razón, muy bueno el ejemplo del toyota! Gracias por responder, abrazo!
